export type PriceBreakdown = {
  sellerType: string;
  basePriceUsd?: number;
  fobPriceUsd?: number;
  sellerDesiredPayoutUsd?: number;
  shippingCostUsd?: number;
  localChargesUsd?: number;
  taxesEstimateUsd?: number;
  insuranceUsd?: number;
  storageUsd?: number;
  clearingFeeUsd?: number;
  landingCostUsd?: number;
  marginUsd?: number;
  platformMarginRatePercent?: number;
  commissionUsd?: number;
  ruleDiscountUsd?: number;
  ruleDiscountRatePercent?: number;
  discountUsd?: number;
  finalPriceUsd: number;
  deliveryDaysMin: number;
  deliveryDaysMax: number;
  currency: string;
};
