export type PriceBreakdown = {
  sellerType: string;
  basePriceRwf?: number;
  fobPriceRwf?: number;
  sellerDesiredPayoutRwf?: number;
  shippingCostRwf?: number;
  localChargesRwf?: number;
  taxesEstimateRwf?: number;
  insuranceRwf?: number;
  storageRwf?: number;
  clearingFeeRwf?: number;
  landingCostRwf?: number;
  marginRwf?: number;
  platformMarginRatePercent?: number;
  commissionRwf?: number;
  ruleDiscountRwf?: number;
  ruleDiscountRatePercent?: number;
  discountRwf?: number;
  finalPriceRwf: number;
  displayPriceRwf?: number;
  finalPriceUsd?: number;
  deliveryDaysMin: number;
  deliveryDaysMax: number;
  currency: string;
};
